sudo: required
services:
  - docker

before_install:
  - docker build -t digitalbrick/docker-react -f Dockerfile.dev .

script:
  - docker run digitalbrick/docker-react npm run test -- --watchAll=false --coverage
