sudo: required
services:
  - docker

before_install:
  - docker build -t digitalbrick/docker-react -f Dockerfile.dev .

script:
  - docker run digitalbrick/docker-react npm run test -- --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-998901271422"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
